language: python
python:
        - "3.5"
install:
        - pip install coverage
        - pip install pytest-cov
        - pip install colored
        - pip install python-coveralls
script:
        - py.test --cov-report term --cov=. test_rpn.py
after_success:
        - coveralls
